googleapis/google-oauth-java-client

.travis.yml

@madongfly, would you mind reviewing?

Enable container Travis-CI building

---

samples/dailymotion-cmdline-sample/pom.xml

This was missed from the bump to 1.23-SNAPSHOT
Fixes #131
@elharo, want to review?

Bump parent version of sample

---

google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/Credential.java

Clarify the differences in where the times are anchored.
Fixes #137

Clarify difference between ExpiresIn and ExpirationTime

---

google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java
google-oauth-client-jetty/src/test/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiverTest.java

Add setter for callback path

---

google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/Credential.java

Reverts google/google-oauth-java-client#153

Revert "Master"

---

.travis.yml
google-oauth-client-appengine/pom.xml
google-oauth-client-java6/pom.xml
google-oauth-client-servlet/pom.xml
google-oauth-client/pom.xml
pom.xml
samples/dailymotion-cmdline-sample/pom.xml

Fixes #166

---

pom.xml

See: https://github.com/google/google-http-java-client/pull/425

docs: document process for updating pom.xml versions

---

google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdToken.java
google-oauth-client/src/test/java/com/google/api/client/auth/openidconnect/IdTokenTest.java
google-oauth-client/src/test/java/com/google/api/client/auth/openidconnect/IdTokenVerifierTest.java

Fix audience validation for OpenID Connect tokens

---

.kokoro/build.sh
.kokoro/common.cfg
.kokoro/presubmit/common.cfg
.kokoro/presubmit/java10.cfg
.kokoro/presubmit/java7.cfg
.kokoro/presubmit/java8.cfg
.kokoro/presubmit/java9.cfg
.kokoro/trampoline.sh

It's expected that the Java 9/10 builds fail. The fixes for those are in #204

Add Kokoro CI config

---

google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/Credential.java

Suggest to call refreshToken() if no token was returned.

Be more helpful in the docs for getAccessToken().

---

google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java

Fix link syntax

---

google-oauth-client-appengine/pom.xml
google-oauth-client-assembly/pom.xml
google-oauth-client-java6/pom.xml
google-oauth-client-jetty/pom.xml
google-oauth-client-servlet/pom.xml
google-oauth-client/pom.xml
pom.xml
samples/dailymotion-cmdline-sample/pom.xml
versions.txt

Bump next snapshot

---

google-oauth-client-bom/README.md
google-oauth-client-bom/pom.xml
pom.xml

Add google-oauth-client-bom artifact

---

google-oauth-client-appengine/pom.xml
google-oauth-client-assembly/pom.xml
google-oauth-client-bom/README.md
google-oauth-client-bom/pom.xml
google-oauth-client-java6/pom.xml
google-oauth-client-jetty/pom.xml
google-oauth-client-servlet/pom.xml
google-oauth-client/pom.xml
pom.xml
samples/dailymotion-cmdline-sample/pom.xml
versions.txt

11-09-2018 12:53 PST
- Add google-oauth-client-bom artifact ([#234](https://github.com/google/google-oauth-java-client/pull/234))
- Release improvements ([#230](https://github.com/google/google-oauth-java-client/pull/230))
- Bump next snapshot ([#229](https://github.com/google/google-oauth-java-client/pull/229))

Release google-oauth-java-client v1.27.0

---

.kokoro/continuous/java11.cfg
.kokoro/presubmit/java11.cfg
README.md
pom.xml

Add Java 11 test configs

---

.kokoro/release/publish_javadoc.cfg
.kokoro/release/publish_javadoc.sh
google-oauth-client-bom/pom.xml
pom.xml

Skips site/javadoc for bom artifact

Add publish_javadoc kokoro job

---

google-oauth-client-appengine/pom.xml
google-oauth-client-appengine/src/main/java/com/google/api/client/extensions/appengine/auth/oauth2/AbstractAppEngineAuthorizationCodeCallbackServlet.java
google-oauth-client-appengine/src/main/java/com/google/api/client/extensions/appengine/auth/oauth2/AbstractAppEngineAuthorizationCodeServlet.java
google-oauth-client-servlet/pom.xml
overview.html
pom.xml
samples/dailymotion-cmdline-sample/instructions.html

Fixes #317 @chingor13 
- [ X] Tests pass
- [ X] Appropriate docs were updated (if necessary)

update URLs, especially pointing to code.google.com

---

pom.xml

remove obsolete parent

---

google-oauth-client-appengine/pom.xml

remove unused and out of date DataNucleus plugin

---

google-oauth-client/pom.xml

Java 7 is now the baseline

---

google-oauth-client-appengine/pom.xml
google-oauth-client-java6/pom.xml
google-oauth-client-jetty/pom.xml
google-oauth-client-servlet/pom.xml
google-oauth-client/pom.xml

fix: add Automatic-Module-Name for all modules

---

pom.xml

@codyoss since renovabot picks the wrong version

chore(deps): update guava to 28.2-android

---

pom.xml

chore(deps): remove mysql dependency

---

pom.xml

deps: remove unused properties

---

.gitignore
checkstyle.xml
pom.xml

@chingor13 @ericraskin This seems necessary to allow us to use try with resources.

deps: update checkstyle plugin

---

google-oauth-client-jetty/pom.xml
google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java
google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/package-info.java
pom.xml

remove references to jetty

---

pom.xml

deps: update to guava 29.0-android

---

samples/dailymotion-cmdline-sample/README.md

chore: fix grammar in README.md 

---

.github/CODEOWNERS
.github/workflows/ci.yaml
.kokoro/build.bat
.kokoro/build.sh
.kokoro/common.sh
.kokoro/dependencies.sh
.kokoro/nightly/integration.cfg
.kokoro/nightly/samples.cfg
.kokoro/populate-secrets.sh
.kokoro/presubmit/integration.cfg
.kokoro/presubmit/samples.cfg
.kokoro/trampoline.sh
.repo-metadata.json
CONTRIBUTING.md
synth.metadata
synth.py

chore: regenerate common templates

---

google-oauth-client/src/main/java/com/google/api/client/auth/oauth/OAuthParameters.java

replace deprecated constructor

---

google-oauth-client-jetty/pom.xml
pom.xml

fix: don't duplicate managed versions

---

pom.xml

chore: remove unused properties

---

google-oauth-client/src/main/java/com/google/api/client/auth/oauth/OAuthParameters.java
google-oauth-client/src/test/java/com/google/api/client/auth/oauth/OAuthParametersTest.java

@BenWhitehead @chingor13 @suztomo run `mvn com.coveo:fmt-maven-plugin:format`
These errors were causing some other PRs to fail.

fix: format

---

docs/oauth-2.0.md
google-oauth-client-assembly/README.md
google-oauth-client-assembly/assembly.xml
google-oauth-client-assembly/classpath-include
google-oauth-client-assembly/properties/jackson-core.jar.properties
pom.xml

@chingor13 per go/json-madness
Actual dependency has already been removed.

deps: remove unused property

---

google-oauth-client-assembly/README.md

docs: eclipse config was unmaintained and deleted

---

.github/workflows/ci.yaml
synth.py

This project does not build on Windows due to DataNucleus.

fix: remove Windows CI build

---

.github/sync-repo-settings.yaml

chore: remove required Kokoro checks

---

google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/TokenRequest.java
google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/TokenRequestTest.java

test: add tests for scopes field in TokenRequest

---

.github/release-please.yml
.github/sync-repo-settings.yaml

build: configure branch 1.31.4-sp as a release branch

---

.github/workflows/ci.yaml
.kokoro/build.sh
.kokoro/presubmit/common.cfg
codecov.yaml
synth.metadata

fix: remove codecov

---

google-oauth-client-bom/pom.xml

build: migrate to new google endpoint on sonatype (#715)

---

.github/release-please.yml
.github/sync-repo-settings.yaml

feat: next release from main branch is 1.33.0

---

.github/.OwlBot.lock.yaml
.github/.OwlBot.yaml

The pull requests in this repository fail Owlbot. Fixing the image URL in the same way as done in https://github.com/googleapis/google-api-java-client/pull/1921/files

chore: fix owlbot image

---

.github/release-please.yml
.github/sync-repo-settings.yaml

feat: next release from main branch is 1.34.0

---

.repo-metadata.json

fix: .repo-metadata.json file #813

---

google-oauth-client/src/test/java/com/google/api/client/auth/openidconnect/IdTokenVerifierTest.java

added a special method to use independent clocks the token timeout check passes for each token
Fixes #950

fix(test): update test tokens

---

.github/sync-repo-settings.yaml

chore: Add auth team as admin.

---

google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java

fix: javadoc fix in IdTokenVerifier

---

google-oauth-client-appengine/pom.xml
google-oauth-client-java6/pom.xml
google-oauth-client-jetty/pom.xml
google-oauth-client-servlet/pom.xml
google-oauth-client/pom.xml
pom.xml

chore: fix broken link for javadoc.

---

.github/release-please.yml
.github/sync-repo-settings.yaml

feat: next release from main branch is 1.39.0

---

README.md

update readme pointers from wiki to ghpages.

chore: update readme to point to ghpages for guide

---

google-oauth-client-appengine/pom.xml
google-oauth-client-assembly/pom.xml
google-oauth-client-bom/pom.xml
google-oauth-client-java6/pom.xml
google-oauth-client-jetty/pom.xml
google-oauth-client-servlet/pom.xml
google-oauth-client/pom.xml
pom.xml
samples/dailymotion-cmdline-sample/pom.xml
samples/keycloak-pkce-cmdline-sample/pom.xml
versions.txt

The change was created by this command after changing versions.txt:
```
sh ../google-cloud-java/generation/apply_current_versions.sh
```

chore: release 1.38.1

---

google-oauth-client-bom/pom.xml

This matches what we have in https://github.com/googleapis/java-shared-config/blob/main/native-image-shared-config/pom.xml#L190C17-L200C32.
b/421886950

deps: maven-gpg-plugin 3.2.7
