google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdToken.java, google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java, google-oauth-client/src/test/java/com/google/api/client/auth/openidconnect/IdTokenVerifierTest.java
Both "accounts.google.com" and "https://accounts.google.com" can be generated
by Google. Let either of them validate. Since the verifier is not aware of the
way the id token was retrieved, simply make the issuers a list and consider any
in the list as equivalent.
-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=106320509
=> Support Google's new issuer that includes scheme

google-oauth-client-jetty/pom.xml, google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java, google-oauth-client-jetty/src/test/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiverTest.java
Fixes #128.
The change in `LocalServerReceiver` is actually very small. Added several unit tests, which verify actual responses of the local server.
PTAL.
=> Implement customizable landing pages after login / use "127.0.0.1" instead of "localhost"

google-oauth-client-appengine/pom.xml, google-oauth-client-assembly/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml
Fixes #125.
Adding metadata to the following modules:
`google-oauth-client`
`google-oauth-client-java6`
`google-oauth-client-servlet`
`google-oauth-client-appengine`
`google-oauth-client-jetty`
I skipped the following module, as it seems to be a special module for assembling a zip:
`google-oauth-client-assembly`
=> Add OSGi Metadata

google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/AuthorizationCodeInstalledApp.java
Certain sites provide an access token without an expiration. Currently this causes a NullPointerException. This change is to allow valid credentials that don't have an expiry.
=> Allow credential without explicit expire time

google-oauth-client-appengine/pom.xml, google-oauth-client-servlet/pom.xml
1. Don’t include the API as servlet containers will need it.
It looks like it may be needed for client-jetty, but that seems to
target a very old version of jetty.
=> Add scope provided to pom.xml

google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/AuthorizationCodeFlow.java
When userId is not specified no requests need to be send to backed, cause it's obvious that user is unknown.
=> google-auth-client: check for empty or null userId

README.md
=> Add maintenance mode note to README.

google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/AuthorizationCodeInstalledApp.java
As outlined in #175 it is desirable in some cases to not use the `java.awt.Desktop` to browse the `authorizationUrl` in `AuthorizationCodeInstalledApp`, e.g. when running a `JavaFX` UI. For that purpose, I created a `Browser` interface with a single `browse(String)` method that is passed as an argument to `AuthorizationCodeInstalledApp`. In order not to introduce any breaking changes, there is also a `DefaultBrowser` that simply delegates to `AuthorizationCodeInstalledApp.browse`.
Fixes #175 
Note: `mvn findbugs:check` fails but it also fails on the `dev` branch.
=> Browser handler

google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java, google-oauth-client-jetty/src/test/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiverTest.java
Currently the LocalServerReceiver callback handler is checking the target against the default CALLBACK_PATH ("/Callback") instead of the user-provided callback path.
This fixes the issue and adds a test to check that a custom callback path is accessible.
=> Use caller-provided callback path for callback handler

google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/AuthorizationCodeInstalledApp.java
Add @Override for browse implementation.
Prior to Java 1.6, this was not allowed, however, we now only support
Java 1.6+.
=> Fix lint warning during import

google-oauth-client-appengine/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml, pom.xml
We're dropping Java 6 in the next release, so set the maven-compiler to use source level 1.7 and to compile to 1.7 binary. Also update animal-sniffer-plugin to java17 to allow 1.7 source.
=> Compile to Java 1.7 binary

google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml
We are bumping the required Java version to 1.7 in the 1.28.0 (next) release.
=> Fix RequiredExecutionEnvironment setting in the OSGI metadata

.kokoro/release/drop.sh, .kokoro/release/promote.sh, google-oauth-client-appengine/pom.xml, google-oauth-client-assembly/pom.xml, google-oauth-client-bom/README.md, google-oauth-client-bom/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml, pom.xml, samples/dailymotion-cmdline-sample/pom.xml, versions.txt
01-07-2019 13:34 PST
- Java 6 support was dropped ([#238](https://github.com/google/google-oauth-java-client/pull/238))
- Fix RequiredExecutionEnvironment setting in the OSGI metadata ([#240](https://github.com/google/google-oauth-java-client/pull/240))
- Add Java 11 test configs ([#239](https://github.com/google/google-oauth-java-client/pull/239))
- Add deprecation annotation for code scheduled for deprecation ([#241](https://github.com/google/google-oauth-java-client/pull/241))
- Update commons-codec 1.6 -> 1.11 ([#242](https://github.com/google/google-oauth-java-client/pull/242))
- Update guava to 26.0-android ([#237](https://github.com/google/google-oauth-java-client/pull/237))
- Bump next snapshot …
=> Release google-oauth-java-client v1.28.0

README.md, google-oauth-client-appengine/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml, pom.xml, versions.txt
Also, stops version bumping the http version when releasing this library - that version bump should be explicit.
=> Update javadoc links to point to googleapis.dev

google-oauth-client-appengine/pom.xml, google-oauth-client-assembly/pom.xml, google-oauth-client-bom/README.md, google-oauth-client-bom/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml, pom.xml, samples/dailymotion-cmdline-sample/pom.xml, versions.txt
05-14-2019 10:09 PDT
- Update google-http-client to 1.29.1
- Drop usage of google-http-client-jdo (removed in 1.29.1)
- Update javadoc links to point to googleapis.dev ([#256](https://github.com/google/google-oauth-java-client/pull/256))
- Add publish_javadoc kokoro job ([#253](https://github.com/google/google-oauth-java-client/pull/253))
- Cleanup assembly proceses ([#243](https://github.com/google/google-oauth-java-client/pull/243))
- Bump next snapshot ([#247](https://github.com/google/google-oauth-java-client/pull/247))
=> Release google-oauth-java-client v1.29.0

google-oauth-client-appengine/pom.xml, google-oauth-client-assembly/pom.xml, google-oauth-client-bom/README.md, google-oauth-client-bom/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml, pom.xml, samples/dailymotion-cmdline-sample/pom.xml, versions.txt
06-03-2019 16:28 PDT
- Update dependency com.google.http-client:google-http-client to v1.29.2 ([#289](https://github.com/google/google-oauth-java-client/pull/289))
=> Release google-oauth-java-client v1.29.2

google-oauth-client-assembly/assembly.xml, google-oauth-client-assembly/properties/google-http-client-jackson.jar.properties, google-oauth-client-assembly/properties/jackson-core-asl.jar.properties, google-oauth-client-java6/pom.xml, google-oauth-client-java6/src/test/java/com/google/api/client/extensions/java6/auth/oauth2/FileCredentialStoreTest.java, google-oauth-client/pom.xml, google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/AuthenticationTestBase.java, google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/AuthorizationCodeFlowTest.java, google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/CustomTokenRequestTest.java, google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/CustomTokenResponseTest.java, google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/TokenErrorResponseTest.java, google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/TokenRequestTest.java, google-oauth-client/src/test/java/com/google/api/client/auth/oauth2/TokenResponseTest.java
Jackson 1.x has been unsupported for a long time. Switch to using the
google-http-client-jackson2 parsing adapter which uses Jackson 2.x.
These usages came only from tests.
=> Convert from google-http-client-jackson to google-http-client-jackson2

google-oauth-client-appengine/pom.xml, google-oauth-client-assembly/pom.xml, google-oauth-client-bom/README.md, google-oauth-client-bom/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml, pom.xml, samples/dailymotion-cmdline-sample/pom.xml, versions.txt
06-05-2019 16:21 PDT
- Convert from google-http-client-jackson to google-http-client-jackson2 ([#302](https://github.com/google/google-oauth-java-client/pull/302))
- Update dependency com.google.http-client:google-http-client to v1.30.0 ([#299](https://github.com/google/google-oauth-java-client/pull/299))
- Update dependency com.google.http-client:google-http-client to v1.29.2 ([#289](https://github.com/google/google-oauth-java-client/pull/289))
- Update dependency org.datanucleus:datanucleus-rdbms to v3.2.13 ([#278](https://github.com/google/google-oauth-java-client/pull/278))
- Update dependency org.codehaus.mojo:findbugs-maven-plugin to v3 ([#283](https://github.com/google/google-oauth-java-client/pull/283))
- Update dependency …
=> Release google-oauth-java-client v1.30.0

google-oauth-client-appengine/pom.xml, google-oauth-client-assembly/pom.xml, google-oauth-client-bom/README.md, google-oauth-client-bom/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml, pom.xml, samples/dailymotion-cmdline-sample/pom.xml, versions.txt
06-06-2019 14:37 PDT
- Update dependency com.google.http-client:google-http-client to v1.30.1 ([#306](https://github.com/google/google-oauth-java-client/pull/306))
- Import google-http-client-bom for dependency management ([#301](https://github.com/google/google-oauth-java-client/pull/301))
- Enable autorelease ([#309](https://github.com/google/google-oauth-java-client/pull/309))
- Bump next snapshot ([#305](https://github.com/google/google-oauth-java-client/pull/305))
=> Release google-oauth-java-client v1.30.1

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Update our CODE_OF_CONDUCT with the latest from OSPO.
Add CONTRIBUTING.md instructions here rather than sending users to developers.google.com.
=> Add CONTRIBUTING.md, Update CODE_OF_CONDUCT.md

google-oauth-client-jetty/pom.xml, google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java, pom.xml
Fixes #233 
Works towards #130
=> Use modern-ish jetty

google-oauth-client-assembly/README.md, google-oauth-client-assembly/assembly.xml, google-oauth-client-assembly/classpath-include, google-oauth-client-assembly/properties/google-http-client-protobuf.jar.properties, google-oauth-client-assembly/properties/protobuf-java.jar.properties, pom.xml
=> deps: remove vestigial, outdated protobuf dependencies

google-oauth-client-jetty/pom.xml, google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java, pom.xml
Remove Jetty v8.2 and replace with com.sun.net.httpserver.HttpServer.  Jetty has had breaking changes since 8.2 (specifically with version 9.4).  This causes conflicts with newer code using later versions of Jetty.  Removing dependency on Jetty resolves this issue.
This replaces previous pull request updating Jetty to 9.4.
Fixes #397.
=> deps: replace Jetty with HttpServer

renovate.json
@chingor13 I think this is what you suggested yesterday.
=> deps: choose android version of Guava with renovabot

.travis.yml
This has not be used for years.
=> chore: remove TravisCI config

.github/workflows/ci.yaml, google-oauth-client-appengine/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, google-oauth-client-servlet/pom.xml, google-oauth-client/pom.xml, samples/dailymotion-cmdline-sample/pom.xml, samples/keycloak-pkce-cmdline-sample/pom.xml
=> deps: fix declared dependencies

google-oauth-client-jetty/pom.xml, google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java, google-oauth-client-jetty/src/test/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiverTest.java
=> fix: don't swallow exceptions in LocalServerReceiver

google-oauth-client/src/main/java/com/google/api/client/auth/oauth/OAuthParameters.java, google-oauth-client/src/test/java/com/google/api/client/auth/oauth/OAuthParametersTest.java
=> fix: oauth1 signing for url encoded content

pom.xml
Updates cloud rad doc generation to use new [doclet](https://github.com/googleapis/java-docfx-doclet). Added the new doclet jar to cloud-devrel-kokoro-resources/docfx bucket
=> chore: update cloud-rad doclet

google-oauth-client/src/main/java/com/google/api/client/auth/oauth/OAuthHmacSha256Signer.java, google-oauth-client/src/test/java/com/google/api/client/auth/oauth/OAuthHmacSha256SignerTest.java
I have added OAuthHmacSha256Signer to enable using the signature method HMAC-SHA256.
Unit test/code coverage has been added in OAuthHmacSha256SignerTest.
This change is necessary for establishing connections to NetSuite as they will no longer accept HMAC-SHA1 as a signature method.
Fixes #702
This replaces pull request #703, which should be closed in favor of this one.  The code is the same (two of the four files modified in the original PR were reverted back to their original versions), so there are only two new files, one class and a test class.
=> feat: Add HMAC-SHA256 signature method for OAuth 1.0

google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/AuthorizationCodeInstalledApp.java, google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/FileCredentialStore.java, google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/VerificationCodeReceiver.java
=> chore: Added throws clause Fixes #598

pom.xml
The dependencies were added in #768. Obviously, `artifactId`s are wrong.
=> chore: remove wrong and ineffective dependencies

.github/sync-repo-settings.yaml, .github/workflows/ci.yaml
We no longer use Linkage Monitor.
=> ci: removing linkage-monitor from required checks

.github/workflows/downstream.yaml, .kokoro/downstream-client-library-check.sh
Test core java libraries in java client libraries before release. Feature/code changes introduced in each PR can be tested on downstream java client libraries by adding `downstream-check:run` label. For now, unit tests are being run.
Next phase involves running samples and integration tests.
Note: Some of these tests are expected to fail due to individual client library conditions and do block the merging of this PR.
=> chore: downstream check for all libraries in single job

google-oauth-client-servlet/src/main/java/com/google/api/client/extensions/servlet/auth/AbstractCallbackServlet.java, google-oauth-client/src/main/java/com/google/api/client/auth/oauth/AbstractOAuthGetToken.java, google-oauth-client/src/main/java/com/google/api/client/auth/oauth/OAuthAuthorizeTemporaryTokenUrl.java, google-oauth-client/src/main/java/com/google/api/client/auth/oauth/OAuthGetAccessToken.java, google-oauth-client/src/main/java/com/google/api/client/auth/oauth/OAuthGetTemporaryToken.java, google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/AuthorizationCodeResponseUrl.java, google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/StoredCredential.java, google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java, samples/dailymotion-cmdline-sample/src/main/java/com/google/api/services/samples/dailymotion/cmdline/DailyMotionUrl.java, samples/dailymotion-cmdline-sample/src/main/java/com/google/api/services/samples/dailymotion/cmdline/Video.java, samples/dailymotion-cmdline-sample/src/main/java/com/google/api/services/samples/dailymotion/cmdline/VideoFeed.java
Fixing the lint problem in this repository by running `mvn com.coveo:fmt-maven-plugin:format`.
=> refactor: fix lint check

google-oauth-client/src/test/java/com/google/api/client/auth/openidconnect/IdTokenVerifierTest.java, google-oauth-client/src/test/resources/certs.json
Use the mock http transport to stub the public key fetching from https://www.googleapis.com/oauth2/v3/certs. Traditionally, these public keys have not rotated (often). For the unit test, we lock the time (for timestamp expiry) and the existing public keys at this point in time.
=> test: fix signature test

pom.xml
Updates the code formatter plugin to match what's in the google-cloud-shared-config. The post-processor seems to automatically run the code formatter, but the version needs to match or the test will not pass.
Related #1058
=> chore: fix code formatting

google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java
This PR restores the interface of the IdTokenVerifier.verify method to avoid a previous breaking [change](https://github.com/googleapis/google-oauth-java-client/pull/934/files#diff-614b71029b58782f8684645ff56c443eac1ab67b0f6736911ae100d7e3971f8f) that was not released yet. It also deprecates the method as it is no longer recommended to use because it can produce false-negatives if public keys for signature verification are not available. 
Here we add the IdTokenVerifier.verifyOrThrow as an alternative that throws IOExceptions if any issues getting public keys.
=> fix: deprecating the IdTokenVerifier.verify, adding verifyOrThrow as an alternative

google-oauth-client-bom/pom.xml, pom.xml
=> ci: profile to upload to GCP Artifact Registry

pom.xml, samples/dailymotion-cmdline-sample/pom.xml, samples/keycloak-pkce-cmdline-sample/pom.xml, samples/pom.xml
Airlock needs newer version of the Maven plugins. We also do not need to declare nexus-staging-maven-plugin by default.
=> ci: Airlock-friendly build dependencies

.github/workflows/ci.yaml, checkstyle.xml, google-oauth-client-assembly/assembly.xml, pom.xml, samples/checkstyle.xml, samples/dailymotion-cmdline-sample/pom.xml, samples/keycloak-pkce-cmdline-sample/pom.xml
Cont. of https://github.com/googleapis/google-oauth-java-client/pull/1135.
=> deps: newer Maven plugin versions for Airlock

pom.xml, samples/dailymotion-cmdline-sample/pom.xml, samples/keycloak-pkce-cmdline-sample/pom.xml
Renaming the recently added "checkstyle" profile to "checkstyle-tests". This profile name matches java-shared-config
https://github.com/googleapis/java-shared-config/blob/2322b789d9568a1cd8ce4efc04fa11d7ff51c178/java-shared-config/pom.xml#L505C11-L505C27 and we can control the plugin invocation in the same Maven command parameter (`-P=-checkstyle-test`)
=> chore: checkstyle-test profile name change

google-oauth-client-appengine/pom.xml, google-oauth-client-java6/pom.xml, google-oauth-client-jetty/pom.xml, pom.xml
b/384085175#comment40
We can skip animal-sniffer-maven-plugin and CLIRR plugin execution if we wrap it as a profile.
=> fix: animal-sniffer and clirr to a profiles

.github/workflows/louhi-tag-release.yaml
b/394646919. This workflow is to experiment release tagging for Louhi tag trigger.
```
suztomo@suztomo2:~/sdk-platform-java$ git log -1 --format=format:%H
0bc9cce6279444b5cd1e33c34e241aa2f6166a70
suztomo@suztomo2:~/sdk-platform-java$ gh pr list --search "0bc9cce6279444b5cd1e33c34e241aa2f6166a70" --state merged --json number --jq '.[].number'
3594
```
"Build with Airlock" check is failing due to b/384085175.
=> ci: Louhi release tag automation

.github/workflows/louhi-tag-release.yaml
The workflow failed with the error message:
> gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
>  env:
>    GH_TOKEN: ${{ github.token }}
https://github.com/googleapis/google-oauth-java-client/actions/runs/13333566853/job/37243408904
=> ci: passing github.token in workflow

.github/workflows/louhi-tag-release.yaml
The latest run didn't substitute the variable correctly: https://github.com/googleapis/google-oauth-java-client/actions/runs/13335726165/job/37250368564
```
PR {PR_NUMBER} for 86a8148d7b6decb8a0b18380111bf77b7e7df763
To https://github.com/googleapis/google-oauth-java-client
* [new tag]         louhi-{PR_NUMBER} -> louhi-{PR_NUMBER}
```
=> ci: fixing typo in louhi release tag automation

.github/release-please.yml, .github/sync-repo-settings.yaml
This reverts commit 389afaa270f2953a5afde593e4f04a245775cb63.
kokoro presubmits only run for branches ending in .x
=> Revert "feat: next release from main branch is 1.39.0 (#1151)"

.github/release-please.yml
With this `tagPullRequestNumber: true` configuration, the Release Please bot will tag the commit SHA with "release-please-<PR number>`.
This information is useful when we create an automation to report the release status back to the pull request.
This configuration change is not exactly a bug fix but "fix:" prefix gives a new release.
=> fix: release-please's tagPullRequestNumber
